plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.4'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id "org.sonarqube" version "5.0.0.4638"
}

apply from: 'gradle/jacoco.gradle'
apply from: 'gradle/junit.gradle'
apply from: 'gradle/lombok.gradle'
apply from: 'gradle/spring.gradle'
apply from: 'gradle/sonar.gradle'

allprojects {
    group = 'com.chaewsstore'
    version = '0.0.1-SNAPSHOT'

    sourceCompatibility = '17'
    targetCompatibility = '17'

    repositories {
        mavenCentral()
    }

    bootJar { enabled = false }
    jar { enabled = true }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'idea'
    apply plugin: 'org.sonarqube'
    compileJava.options.encoding = 'UTF-8'

    dependencies {
        implementation 'org.apache.commons:commons-collections4:4.4'
    }
    sonar {
        properties {
            property 'sonar.java.binaries', "${buildDir}/classes"
        }
    }
}
