plugins {
    id 'java'
    id 'org.asciidoctor.jvm.convert' version '3.3.2'
}

bootJar { enabled = true }
jar { enabled = false }

apply from: '../gradle/asciidoc.gradle'

dependencies {
    implementation project(':global-utils')
    implementation project(':chaewsstore-core:domain')
    implementation project(':chaewsstore-core:infra')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    runtimeOnly 'com.h2database:h2'

    // Security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'
}
