server:
  port: 8001

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/chaewsstore
    username: sa

  jpa:
    hibernate:
      hibernate.hbm2ddl.auto: update
    show-sql: true
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
jwt:
  header: Authorization
  secret: ${SECRET_KEY}

logging.level.org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
